apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gopasal
resources:
  - namespace.yaml
  - configmap.yaml
  - migration-job.yaml
  - workloads.yaml
  - clamav.yaml
  - ingress.yaml
  - policies.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: gopasal
