import { IsString, Matches, MaxLength, MinLength } from "class-validator";

/** IDs are generated by Prisma today, but the route accepts opaque safe IDs. */
export class SavedShopParamsDto {
  @IsString()
  @MinLength(1)
  @MaxLength(64)
  @Matches(/^[A-Za-z0-9_-]+$/)
  shopId!: string;
}

export class SavedProductParamsDto {
  @IsString()
  @MinLength(1)
  @MaxLength(64)
  @Matches(/^[A-Za-z0-9_-]+$/)
  productId!: string;
}
