apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gopasal-staging
resources:
  - ../../base
nameSuffix: -staging
images:
  - { name: registry.example.invalid/gopasal/api, newTag: staging-replace-me }
  - { name: registry.example.invalid/gopasal/customer, newTag: staging-replace-me }
  - { name: registry.example.invalid/gopasal/seller, newTag: staging-replace-me }
  - { name: registry.example.invalid/gopasal/admin, newTag: staging-replace-me }
  - { name: registry.example.invalid/gopasal/rider, newTag: staging-replace-me }
patches:
  - path: environment.yaml
